image: node:latest  # Use the latest Node.js image

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install -g npm  # Ensure npm is up to date
          - npm install           # Install dependencies
          - npx playwright install  # Install Playwright browsers
          - npm run test      # Run end-to-end tests